### ISSUE TITLE
Quale "AMAT OSM Server Url"?

### ISSUE THREAD

**Issue by emmexx** [amat-mi/AMATOSMEditor#11]
Ho provato ad utilizzare il plugin e dopo qualche difficolta' d'installazione (sul wiki di OSM le istruzioni sono leggermente fuorvianti, e' presente il link al file jar ma utilizzando quello il plugin non viene caricato da josm; andando direttamente su github e scaricando in RAW il file, il plugin funziona) il plugin e' presente in josm. Solo che non e' chiaro come usarlo.
Nel wiki di OSM non ci sono indicazioni relative alla configurazione del plugin. Su github invece c'e' l'indicazione di inserire http://127.0.0.1:8000/osm/api.
Nel primo caso, cioe' se non inserisco la stringa di connessione, nel menu Data le voci relative al plugin restano disabilitate.
Nle secondo caso, cioe' se inserisco http://127..., la voce AMAT Download e' attiva ma utilizzandola appare il seguente messaggio d'errore:

Failed to pen a connection to the remote server 'AMAT OSM Server'.
Please check your internet connection.

Suppongo che il problema derivi dalla connessione a localhost o dal fatto che serva un indirizzo pubblico al server AMAT.
Mi pare d'aver letto attentamente le istruzioni ma evidentemente mi e' sfuggito qualcosa. Cosa?
grazie
  maxx

**Comment by caipirginka** [comment]
Chiedo scusa per il ritardo nella risposta...
Scusa la domanda, ma sei un collaboratore di AMAT, o hai trovato il plugin per caso...???
Il plugin AMATOSMEditor funziona, per ora, solo in abbinamento ad un server interno, quindi non è di utilizzo generale, anche se, con un po', di lavoro, potrebbe diventarlo...
Il file .jar deve effettivamente essere scaricato in RAW, insieme, volendo ad un file .css apposito:
    
    https://github.com/amat-mi/AMATOSMEditor/raw/master/AMATOSMEditor.jar
    https://raw.github.com/amat-mi/AMATOSMEditor/master/data/AMATOSMEditor.mapcss

Per quanto riguarda l'indirizzo del server, deve essere specificato quello di un qualunque server che risponda alle API OSM versione 0.6.

Ciao
Paolo

**Comment by emmexx** [comment]
Sono un collaboratore di OSM! :-)
Siccome il tag loc_ref e' molto diffuso nelle way di Milano mi ero autoconvinto che il plugin fosse usato da vari mappatori, non solo da AMAT.
Anche la presenza della pagina wiki non fa pensare a qualcosa ad uso interno AMAT, forse sarebbe meglio  specificarlo.

Pensavo di usare il plugin perche' ho inserito/modificato alcune way e volevo aggiungere anche il tag loc_ref.

grazie lo stesso
   maxx
